frequency: daily
datasets:
  - name: "main"
    source: "parsec"
    query: >
      with cte as (
        select
          n.region,
          r.*,
          date_trunc('day', r.created_at) date,
          row_number() over (partition by r.cid, n.region order by r.created_at) request_number
        from retrievals_ecs r
          inner join nodes_ecs n on r.node_id = n.id
        where n.fleet = 'cid.contact' and r.error is null
          and r.created_at >= {{ .StartOfDay | timestamptz }} - '30 days'::interval
          and r.created_at < {{ .StartOfDay | timestamptz }}
      )
      select
          cte.date,
          percentile_cont(0.5) within group (order by cte.duration) filter ( where cte.request_number = 1 ) p50_uncached,
          percentile_cont(0.9) within group (order by cte.duration) filter ( where cte.request_number = 1 ) p90_uncached,
          percentile_cont(0.5) within group (order by cte.duration) filter ( where cte.request_number = 2 ) p50_cached,
          percentile_cont(0.9) within group (order by cte.duration) filter ( where cte.request_number = 2 ) p90_cached
      from cte
      group by cte.date
      order by cte.date

series:
  - type: "line"
    name: "p50 (cached)"
    dataset: "main"
    labels: "date"
    values: "p50_cached"
  - type: "line"
    name: "p90 (cached)"
    dataset: "main"
    labels: "date"
    values: "p90_cached"
  - type: "line"
    name: "p50 (uncached)"
    dataset: "main"
    labels: "date"
    values: "p50_uncached"
  - type: "line"
    name: "p90 (uncached)"
    dataset: "main"
    labels: "date"
    values: "p90_uncached"

layout:
  legend:
    orientation: "h"
    x: 0.01
    y: 1.1
    xanchor: "left"
  xaxis:
    title:
      text: "Date"
      standoff: 1
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Latency in s"
  margin:
    pad: 1
    t: 30
    l: 50
    r: 20
    b: 60
  title:
    font:
      size: 10
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-30"  | simpledate}} - {{ .EndOfPreviousDay | simpledate }} ({{ .Params.ipni }})'
    x: 1
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
