frequency: daily
datasets:
  - name: "current"
    source: "tiros"
    query: >
      select
          m.website,
          r.region,
          percentile_cont(0.{{ .Params.percentile }}) within group (order by m.{{ .Params.metric }}) p{{ .Params.percentile }}
      from measurements m
               inner join runs r on r.id = m.run_id
      where m.created_at >= {{ .StartOfDay | timestamptz }} - '1 week'::interval
        and m.created_at < {{ .StartOfDay | timestamptz }}
        and m.type = '{{ .Params.type }}'
        and m.status_code >= 200
        and m.status_code < 400
        and (r.ipfs_impl = '{{ .Params.impl }}' or '{{ .Params.type }}' = 'HTTP')
      group by r.region, m.website;

tables:
  - type: "heatmap"
    name: "{{ .Params.metric | toUpper }}"
    dataset: "current"
    xLabels: "region"
    yLabels: "website"
    values: "p{{ .Params.percentile }}"
    colorbar:
      title:
        text: "Latency in s"
        side: "right"

# {{ $title_label := .Params.type }}
# {{ if eq .Params.type "IPFS" }}
#   {{ $title_label = .Params.impl }}
# {{ end }}

layout:
  automargin: true
  margin:
    b: 30
  title:
    font:
      size: 10
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-7"  | simpledate}} - {{ .EndOfPreviousDay | simpledate }} (p{{ .Params.percentile }}, {{ .Params.metric }}, {{ $title_label }}). Source: Tiros.'
    x: 0.99
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  xaxis:
    title:
      text: AWS Region
    side: top
    automargin: true
  yaxis:
    title:
      text: Website
    automargin: true
  dragmode: false

config:
  modebarbuttonstoremove:
    - zoom2d
    - pan2d
    - select2d
    - lasso2d
    - zoomIn2d
    - zoomOut2d
    - autoScale2d
    - resetScale2d
