frequency: daily
datasets:
  - name: "ipfs"
    source: "caracol"
    query: >
      select date, value from get_collected_values(10, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});
  - name: "ipns"
    source: "caracol"
    query: >
      select date, value from get_collected_values(9, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});

series:
  - type: "bar"
    name: "IPFS"
    dataset: "ipfs"
    labels: date"
    values: "value"

  - type: "bar"
    name: "IPNS"
    dataset: "ipns"
    labels: "date"
    values: "value"


layout:
  barmode: stack
  title:
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-90"  | simpledate}} to {{ .EndOfPreviousDay | simpledate }}'
    font:
      size: 10
    x: 0.99
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  legend:
    orientation: "h"
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Number of requests"
