frequency: daily
datasets:
  - name: "europe"
    source: "caracol"
    query: >
      select date, value from get_collected_values(13, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});
  - name: "asia se"
    source: "caracol"
    query: >
      select date, value from get_collected_values(14, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});
  - name: "na east"
    source: "caracol"
    query: >
      select date, value from get_collected_values(15, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});
  - name: "na west"
    source: "caracol"
    query: >
      select date, value from get_collected_values(16, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});

series:
  - type: "bar"
    name: "Europe"
    dataset: "europe"
    labels: "date"
    values: "value"
    color: "region-europe"
  - type: "bar"
    name: "Southeast Asia"
    dataset: "asia se"
    labels: "date"
    values: "value"
    color: "region-asia"
  - type: "bar"
    name: "North America East"
    dataset: "na east"
    labels: "date"
    values: "value"
    color: "region-north-america-east"
  - type: "bar"
    name: "North America West"
    dataset: "na west"
    labels: "date"
    values: "value"
    color: "region-north-america-west"


layout:
  barmode: stack
  title:
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-90"  | simpledate}} to {{ .EndOfPreviousDay | simpledate }}. Source: ipfs.io / dweb.link access logs'
    font:
      size: 10
    x: 0.99
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  legend:
    orientation: "h"
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Number of requests"
