frequency: daily
datasets:
  - name: "IPNI total requests"
    source: "static"
    query: >
      {
        "x": [
          "2023-03-13T00:00:00Z",
          "2023-03-14T00:00:00Z",
          "2023-03-15T00:00:00Z",
          "2023-03-16T00:00:00Z",
          "2023-03-17T00:00:00Z",
          "2023-03-18T00:00:00Z",
          "2023-03-19T00:00:00Z",
          "2023-03-20T00:00:00Z",
          "2023-03-21T00:00:00Z",
          "2023-03-22T00:00:00Z",
          "2023-03-23T00:00:00Z",
          "2023-03-24T00:00:00Z",
          "2023-03-25T00:00:00Z",
          "2023-03-26T00:00:00Z",
          "2023-03-27T00:00:00Z",
          "2023-03-28T00:00:00Z",
          "2023-03-29T00:00:00Z",
          "2023-03-30T00:00:00Z",
          "2023-03-31T00:00:00Z",
          "2023-04-01T00:00:00Z",
          "2023-04-02T00:00:00Z",
          "2023-04-03T00:00:00Z",
          "2023-04-04T00:00:00Z",
          "2023-04-05T00:00:00Z",
          "2023-04-06T00:00:00Z",
          "2023-04-07T00:00:00Z",
          "2023-04-08T00:00:00Z",
          "2023-04-09T00:00:00Z",
          "2023-04-10T00:00:00Z",
          "2023-04-11T00:00:00Z",
          "2023-04-12T00:00:00Z"
        ],
        "y": [
          52137730,
          50747513,
          59946999,
          105854281,
          84781023,
          82860712,
          94525181,
          89482830,
          88255444,
          84375861,
          72385711,
          76774808,
          82145621,
          85764326,
          80491168,
          83328231,
          81535411,
          92845473,
          84501372,
          81453270,
          103162245,
          104488182,
          102674285,
          78930125,
          63788246,
          69584733,
          63460855,
          49108999,
          48838955,
          49621010,
          42589712
        ]
      }

series:
  - type: "bar"
    name: "Total"
    dataset: "IPNI total requests"
    labels: "x"
    values: "y"


layout:
  title:
    text: "IPNI Requests (30 days to 12 Apr 2023)"
  legend:
    orientation: "h"
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Number of requests"
