frequency: weekly
datasets:
  - name: "main"
    source: "nebula_ipfs"
    query: >
      with av as (
        select id,
             case
            when position('@' in agent_version) = 0 then
              case
                when position('github.com' in agent_version) != 0 then split_part(agent_version, '/',3)
                else split_part(agent_version, '/',1)
              end
            else
              case
                when position('github.com' in agent_version) != 0 then split_part(split_part(agent_version, '@',1), '/',3)
                else split_part(split_part(agent_version, '@',1), '/',1)
              end
              end as agent,
             case
            when position('@' in agent_version) = 0 then split_part(split_part(agent_version, '/',2), '-',1)
            else split_part(agent_version, '@',2)
             end as version
        from agent_versions
      )

      select concat(av.agent, ' ', av.version) as agentversion, count(DISTINCT v.peer_id) as number
      from visits v join av on av.id=v.agent_version_id
        where
                v.visit_started_at >= {{ .StartOfWeek | timestamptz }}-'1 week'::interval
                and v.visit_started_at < {{ .StartOfWeek | timestamptz }}
                AND v.type = 'crawl' AND v.connect_error IS NULL
                and (av.agent = 'go-ipfs' or av.agent = 'kubo')
        group by av.agent, av.version
        order by cast(split_part(av.version, '.',1) as numeric)*10000+cast(split_part(av.version, '.',2) as numeric)*100+cast(split_part(av.version, '.',3) as numeric);

series:
  - type: "hbar"
    name: "versions"
    dataset: "main"
    labels: "agentversion"
    values: "number"

layout:
  title:
    text: "Kubo version distribution"
  yaxis:
    automargin: true
